# Generated by Django 3.0.10 on 2020-09-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20200915_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Слаг'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=250, verbose_name='Компания')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.City', verbose_name='Город')),
                ('id_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.Language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
