# Generated by Django 3.0.10 on 2020-09-30 20:16

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import scrap.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', jsonfield.fields.JSONField(default=scrap.models.default_urls)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.City', verbose_name='Город')),
                ('id_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.Language', verbose_name='Язык')),
            ],
            options={
                'unique_together': {('id_city', 'id_language')},
            },
        ),
    ]
